### ISSUE TITLE
cividis as hex color codes

### ISSUE THREAD

**Issue by smsaladi** [pnnl/cmaputil#1]
Would it be possible to provide the cividis colormap as 256 hex color codes? I'm not entirely familiar with the file formats in the [`colormaps`](https://github.com/pnnl/cmaputil/tree/master/colormaps) folder; otherwise, I may have been able to figure this out myself.

**Comment by smsaladi** [comment]
I see 3c87d1d thanks!

**Comment by jamienunez** [comment]
No problem! Sorry for the wait, I didn't see your request until yesterday!

By the way, in case you needed this for R, check out this R package that was just released: https://github.com/marcosci/cividis
